# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]

#env:
#  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2.0.2

      - run: npm i
#      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build
      - run: npx nx affected --target=lint
#      - run: npx nx-cloud stop-all-agents

